name: Debug Sync v3

env:
  UPSTREAM_URL: "https://github.com/ros2/ros2_documentation.git"
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  UPSTREAM_BRANCH: "rolling"
  DOWNSTREAM_BRANCH: "rolling"
  FETCH_ARGS: ""
  MERGE_ARGS: ""
  PUSH_ARGS: ""
  SPAWN_LOGS: "false" # "true" or "false"
on:
  workflow_dispatch:
  push:
    branches:
      - rolling
  schedule:
    - cron: '8/5 * * * *'
  
jobs:
  debug:
    runs-on: ubuntu-22.04
    steps:
    run:  x=${{ toJson(github.event.issue.labels) }} && echo $x

  sync:    
    if: ! (github.event.issue.labels.*.name, 'automatic-sync-merge') # do not run if there is a active sync merge issue        
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Sync and merge  documentation
                uses: jsduenass/sync-docs@v0.alpha
        with:
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ env.WORKFLOW_TOKEN }}
          fetch_args: ${{ env.FETCH_ARGS }}
          merge_args: ${{ env.MERGE_ARGS }}
          push_args: ${{ env.PUSH_ARGS }}
          spawn_logs: ${{ env.SPAWN_LOGS }}
